### ISSUE TITLE
How to deal with varying length video? Thanks

### ISSUE THREAD

**Issue by junyongyou** [lucidrains/TimeSformer-pytorch#11]
Dear all, I am wondering if TimeSformer can handle different videos with diverse lengths? Is it possible to use mask as the original Transformer? Any ideas, thanks a lot.

**Comment by lucidrains** [comment]
@junyongyou Hi Junyong! Let me know if https://github.com/lucidrains/TimeSformer-pytorch/releases/tag/1.2.0 works!

**Comment by junyongyou** [comment]
> 
> 
> @junyongyou Hi Junyong! Let me know if https://github.com/lucidrains/TimeSformer-pytorch/releases/tag/1.2.0 works!

Excellent. I will try that. Thanks a lot.
