### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by dmenig** [lucidrains/TimeSformer-pytorch#2]
Hi. Do you have any pretrained model on kinetics so we can test the results and maybe transfer, please ?

Thank you in advance.

**Comment by OValery16** [comment]
Thank you for this brilliant work. I would like to reproduce the result of your paper. Can you  provide the weights of your model and the code used to train this model ?

**Comment by lucidrains** [comment]
Hi all! I'm actually not the paper author, and I don't believe the official code or weights have been released yet

**Comment by dmenig** [comment]
Ok then. Thanks anyways.
